name: Deploy to Railway

on: [push, pull_request]

jobs:
 Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install
      - name: npm run Build
        run: npm run build
        
 deploy:
           name: Railway Deploy
           runs-on: ubuntu-latest
           needs: Build
           steps:
             - uses: actions/checkout@v3
             - uses: devtomio/action-railway@v1.1.4
               name: Deploy to Railway
               env:
                 RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
