name: Deploy to Railway

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build for production
        run: npm run build
      - name: Deploy to Railway
      - uses: actions/checkout@v3
      - uses: devtomio/action-railway@v1.1.4
        env:
           RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  
